config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :orders
  resources :line_items
  resources :carts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users do
    resources :reviews
  end

  resources :products do
    resources :reviews
    resources :favorites, only: [:create, :destroy], shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  get "search", to: "search#search"

  get "purchase_history", to: "users#purchase_history"
  get "chat", to: "users#chat"
  get "admin_products", to: "users#admin_products"
  get "admin_users", to: "users#admin_users"
  get "admin_orders", to: "users#admin_orders"

  get "product_for_women", to: "products#product_for_women"
  get "product_for_men", to: "products#product_for_men"
  get "sneakers_product", to: "products#sneakers_product"
  get "sandals_product", to: "products#sandals_product"
  get "shoes_product", to: "products#shoes_product"
  get "boots_product", to: "products#boots_product"
  get "flip_flops_product", to: "products#flip_flops_product"

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

  get "recommend_product", to: "users#recommend_product"

  get "cf_product", to: "users#cf_product"

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
end

app/views/shared/_cart_header.html.erb
<i class="flaticon-bag"></i>
<span><%= current_cart.line_items.size %></span>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<section class="footer-section">
  <div class="social-links-warp">
    <div class="container">
      <div class="social-links">
        <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
        <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
        <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
        <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
        <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
        <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
        <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
      </div>
    </div>
  </div>
</section>

app/views/shared/_header.html.erb
<header class="header-section">
  <div class="header-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 text-center text-lg-left">
          <a href="http://localhost:3000" class="site-logo">
            <h2>Home</h2>
          </a>
        </div>
        <div class="col-xl-6 col-lg-5">
          <!-- <form class="header-search-form">
            <input type="text" placeholder="Search on product...">
            <button><i class="flaticon-search"></i></button>
          </form> -->
          <!-- <form class="header-search-form"> -->
          <div class="header-search-form">
            <%= form_for :term, url: search_path, method: :get do |form| %>
              <%= text_field_tag :term, params[:term], placeholder: "Search on product..." %>
              <button><i class="flaticon-search"></i></button>
            <% end %>
          </div>
          <!-- </form> -->
        </div>
        <div class="col-xl-4 col-lg-5">
          <div class="user-panel">
            <div class="up-item">
              <i class="flaticon-profile"></i>
              <% if user_signed_in? %>
                <%= link_to "#{current_user.email}", user_path(current_user) %>

                <% if current_user.role == 1 %>
                  <%= link_to "/admin" do %>
                    <ion-icon name="settings"></ion-icon>Admin page
                  <% end %>
                <% else %>
                  <div class="up-item">
                    <div class="shopping-card" id="cart-header">
                      <%= render "shared/cart_header" %>
                    </div>
                    <%= link_to "Shopping Cart", cart_path(current_cart) %>
                  </div>
                <% end %>
              <% else %>
                <%= link_to "Sign In", new_user_session_path %> or <%= link_to "Create Account", new_user_registration_path %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="main-navbar">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.role == 1 %>
          <ul class="main-menu">
            <li><%= link_to "Users", admin_users_path %></li>
            <li><%= link_to "Products", admin_products_path %></li>
            <li><%= link_to "Orders", product_for_men_path %></li>
          </ul>
        <% else %>
          <!-- menu -->
          <ul class="main-menu">
            <li><a href="/">Home</a></li>
            <li><%= link_to "Women", product_for_women_path %></li>
            <li><%= link_to "Men", product_for_men_path %></li>
            <!-- <li><a href="#">Jewelry
              <span class="new">New</span>
            </a></li> -->
            <li><a href="#">HOTS</a>
              <ul class="sub-menu">
                <li><%= link_to "Sneakers", sneakers_product_path %></li>
                <li><%= link_to "Sandals", sandals_product_path %></li>
                <li><%= link_to "Formal Shoes", shoes_product_path %></li>
                <li><%= link_to "Boots", boots_product_path %></li>
                <li><%= link_to "Flip Flops", flip_flops_product_path %></li>
              </ul>
            </li>

            <% if user_signed_in? %>
              <li><%= link_to "Recommend product", cf_product_path %></li>

              <li style="float: right;">
                <%= link_to purchase_history_path do %>
                  <i class="flaticon-bag"></i>Purchase History
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% else %>
        <!-- menu -->
        <ul class="main-menu">
          <li><a href="/">Home</a></li>
          <li><%= link_to "Women", product_for_women_path %></li>
          <li><%= link_to "Men", product_for_men_path %></li>
          <!-- <li><a href="#">Jewelry
            <span class="new">New</span>
          </a></li> -->
          <li><a href="#">HOTS</a>
            <ul class="sub-menu">
              <li><%= link_to "Sneakers", sneakers_product_path %></li>
              <li><%= link_to "Sandals", sandals_product_path %></li>
              <li><%= link_to "Formal Shoes", shoes_product_path %></li>
              <li><%= link_to "Boots", boots_product_path %></li>
              <li><%= link_to "Flip Flops", flip_flops_product_path %></li>
            </ul>
          </li>

          <% if user_signed_in? %>
            <li><%= link_to "Recommend product", cf_product_path %></li>

            <li style="float: right;">
              <%= link_to purchase_history_path do %>
                <i class="flaticon-bag"></i>Purchase History
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </nav>
</header>