config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :orders
  resources :line_items
  resources :carts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users do
    resources :reviews
  end

  resources :products do
    resources :reviews
    resources :favorites, only: [:create, :destroy], shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  get "search", to: "search#search"

  get "purchase_history", to: "users#purchase_history"
  get "chat", to: "users#chat"
  get "admin_products", to: "users#admin_products"
  get "admin_users", to: "users#admin_users"
  get "admin_orders", to: "users#admin_orders"

  get "product_for_women", to: "products#product_for_women"
  get "product_for_men", to: "products#product_for_men"
  get "sneakers_product", to: "products#sneakers_product"
  get "sandals_product", to: "products#sandals_product"
  get "shoes_product", to: "products#shoes_product"
  get "boots_product", to: "products#boots_product"
  get "flip_flops_product", to: "products#flip_flops_product"

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

  get "recommend_product", to: "users#recommend_product"

  get "cf_product", to: "users#cf_product"

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    # current_item.price_unit = product_id.discounted_price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = []
    if session[:cart_id] != nil
      @carts << Cart.find_by_id(session[:cart_id])
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to '/', notice: "Cart is empty" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="page-top-info">
  <div class="container">
    <h4>Your cart</h4>
    <div class="site-pagination">
      <a href="">Home</a> /
      <a href="">Your cart</a>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- cart section end -->
<section class="cart-section spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="cart-table">
          <h3>Your Cart</h3>
          <div class="cart-table-warp">
            <table>
              <thead>
                <tr>
                  <th class="product-th">Product</th>
                  <th class="quy-th">Quantity</th>
                  <th class="size-th">Size</th>
                  <th class="total-th">Price</th>
                </tr>
              </thead>
              <tbody>
                <%= render cart.line_items %>
              </tbody>
            </table>
          </div>
          <div class="total-cost">
            <h6>Total <span><%= number_to_currency(cart.total_price) %></span></h6>
          </div>
        </div>
      </div>
      <div class="col-lg-4 card-right">
        <%= button_to 'Empty cart', cart, class: "site-btn sb-dark", :method => :delete, data: {:confirm => 'Are you sure?' } %>
        <%= button_to 'Checkout', new_order_path, :method => :get, class: "site-btn" %>
        <a href="/" class="site-btn sb-dark">Continue shopping</a>
      </div>
    </div>
  </div>
</section>
<!-- cart section end -->

<!-- Related product section -->
<section class="related-product-section">
  <div class="container">
    <div class="section-title text-uppercase">
      <h2>Continue Shopping</h2>
    </div>
    <div class="row">
      <% 4.times do %>
        <%= render "products/random_product", {product: random_product } %>
      <% end %>
    </div>
  </div>
</section>

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/edit.html.erb
<%= form_with(model: @cart, local: true) do |form| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="page-top-info">
    <div class="container">
      <h4>Your cart</h4>
      <div class="site-pagination">
        <a href="">Home</a> /
        <a href="">Your cart</a>
      </div>
    </div>
  </div>
  <!-- Page info end -->


  <!-- cart section end -->
  <section class="cart-section spad">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="cart-table">
            <h3>Edit Your Cart</h3>
            <div class="cart-table-warp">
              <table>
                <thead>
                  <tr>
                    <th class="product-th">Product</th>
                    <th class="quy-th">Quantity</th>
                    <th class="size-th">Size</th>
                  </tr>
                </thead>
                <tbody>
                  <% @cart.line_items.each do |line_item| %>
                    <tr>
                      <td class="product-col">
                        <img><%= image_tag(line_item.product.image.split(/,/).first) %>
                        <div class="pc-title">
                          <h4><%= line_item.product.product_name %></h4>
                          <p>$<%= line_item.price_unit %></p>
                        </div>
                      </td>
                      <td class="quy-col">
                        <div class="quantity">
                          <div class="pro-qty">
                            <input type="text" value="<%= line_item.quantity %>">
                          </div>
                        </div>
                      </td>
                      <td class="size-col"><h4>Size M</h4></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div>
              <%= form.submit %>
            </div>
          </div>
        </div>
        <div class="col-lg-4 card-right">
          <%= button_to 'Empty cart', @cart, class: "site-btn sb-dark", :method => :delete, data: {:confirm => 'Are you sure?' } %>
          <%= button_to 'Checkout', new_order_path, :method => :get, class: "site-btn" %>
          <a href="/" class="site-btn sb-dark">Continue shopping</a>
        </div>
      </div>
    </div>
  </section>
  <!-- cart section end -->

  <!-- Related product section -->
  <section class="related-product-section">
    <div class="container">
      <div class="section-title text-uppercase">
        <h2>Continue Shopping</h2>
      </div>
      <div class="row">
        <% 4.times do %>
          <%= render "products/random_product", {product: random_product } %>
        <% end %>
      </div>
    </div>
  </section>

<% end %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>