config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :orders
  resources :line_items
  resources :carts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users do
    resources :reviews
  end

  resources :products do
    resources :reviews
    resources :favorites, only: [:create, :destroy], shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  get "search", to: "search#search"

  get "purchase_history", to: "users#purchase_history"
  get "chat", to: "users#chat"
  get "admin_products", to: "users#admin_products"
  get "admin_users", to: "users#admin_users"
  get "admin_orders", to: "users#admin_orders"

  get "product_for_women", to: "products#product_for_women"
  get "product_for_men", to: "products#product_for_men"
  get "sneakers_product", to: "products#sneakers_product"
  get "sandals_product", to: "products#sandals_product"
  get "shoes_product", to: "products#shoes_product"
  get "boots_product", to: "products#boots_product"
  get "flip_flops_product", to: "products#flip_flops_product"

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

  get "recommend_product", to: "users#recommend_product"

  get "cf_product", to: "users#cf_product"

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
end

app/models/product.rb
require "elasticsearch/model"

class Product < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  searchkick

  has_many :favorites
  has_many :users, through: :favorites

  has_many :line_items
  has_many :reviews

  before_destroy :check_if_has_line_item

  paginates_per 8

  def is_favorited user
    if user
      Favorite.find_by(user_id: user.id, product_id: id)
    end
  end

  def liked_by
    return self.reviews.select {|user| user.product_rating >= 3}
  end

  def disliked_by
    return self.reviews.select {|user| user.product_rating < 3}
  end

private

    def check_if_has_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'This product has a LineItem')
            return false
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.page params[:page]
    @cart = current_cart
    @top_reviews = Product.all.order(:overall_rating => :desc)
    @top_views = Product.all.order(:view_count => :desc)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @is_favorited = @product.is_favorited(current_user)
    @reviews = @product.reviews.to_a

    @product = Product.find_by_id params[:id]
    recent_products.push @product #=> Đẩy 1 product vừa xem vào collection

    view_count = @product.view_count + 1
    @product.update_attributes(view_count: view_count)

    # Lấy toàn bộ danh sách
    recent_products

    @similar_products = Product.search("#{@product.product_category_tree.split(/>>/).reverse.second}")
    ssize = @similar_products.size
    @product1 = @similar_products[rand(ssize)]
    @product2 = @similar_products[rand(ssize)]
    @product3 = @similar_products[rand(ssize)]
    @product4 = @similar_products[rand(ssize)]
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def product_for_women
    products = Product.search("women")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def product_for_men
    products = Product.search("men")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def sneakers_product
    products = Product.search("sneakers")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def boots_product
    products = Product.search("boots")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def shoes_product
    products = Product.search("shoes")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def sandals_product
    products = Product.search("sandals")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  def flip_flops_product
    products = Product.search("flip flops")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:uniq_id, :crawl_timestamp, :product_url, :product_name, :product_category_tree, :pid, :retail_price, :discounted_price, :image, :is_FK_Advantage_product, :description, :product_rating, :overall_rating, :brand, :product_specifications)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite_icon.html.erb
<% if is_favorited.present? %>
  <%= link_to favorite_path(is_favorited), class: "wishlist-btn", method: :delete, remote: true do %>
    <i class="flaticon-heart" style="color: red;"></i>
  <% end %>
<% else %>
  <%= link_to product_favorites_path(product), class: "wishlist-btn", method: :post, remote: true do %>
    <i class="flaticon-heart"></i>
  <% end %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uniq_id %>
    <%= form.text_field :uniq_id, id: :product_uniq_id %>
  </div>

  <div class="field">
    <%= form.label :crawl_timestamp %>
    <%= form.text_field :crawl_timestamp, id: :product_crawl_timestamp %>
  </div>

  <div class="field">
    <%= form.label :product_url %>
    <%= form.text_field :product_url, id: :product_product_url %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :product_product_name %>
  </div>

  <div class="field">
    <%= form.label :product_category_tree %>
    <%= form.text_field :product_category_tree, id: :product_product_category_tree %>
  </div>

  <div class="field">
    <%= form.label :pid %>
    <%= form.text_field :pid, id: :product_pid %>
  </div>

  <div class="field">
    <%= form.label :retail_price %>
    <%= form.text_field :retail_price, id: :product_retail_price %>
  </div>

  <div class="field">
    <%= form.label :discounted_price %>
    <%= form.text_field :discounted_price, id: :product_discounted_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :product_image %>
  </div>

  <div class="field">
    <%= form.label :is_FK_Advantage_product %>
    <%= form.text_field :is_FK_Advantage_product, id: :product_is_FK_Advantage_product %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :product_rating %>
    <%= form.text_field :product_rating, id: :product_product_rating %>
  </div>

  <div class="field">
    <%= form.label :overall_rating %>
    <%= form.text_field :overall_rating, id: :product_overall_rating %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="field">
    <%= form.label :product_specifications %>
    <%= form.text_field :product_specifications, id: :product_product_specifications %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-lg-3 col-sm-6" style="margin-top: 5px;">
  <div class="product-item">
    <div class="pi-pic">
      <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
      <div class="pi-links">
        <%= link_to product_path(product.id), class: "add-card" do %>
          <i class="flaticon-bag"></i><span>ADD TO CART</span>
        <% end %>
        <div class="product-favorite" id="favorite-icon-product-<%= product.id.to_s %>">
          <%= render "products/favorite_icon", {is_favorited: product.is_favorited(current_user), product: product} %>
        </div>
      </div>
    </div>
    <div class="pi-text">
      <h6><%= product.discounted_price %>$</h6>
      <p><%= product.product_name %></p>
    </div>
  </div>
</div>
<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.product_name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.discounted_price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/_random_product.html.erb
<div class="col-lg-3 col-sm-6">
  <div class="product-item">
    <div class="pi-pic">
      <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
      <div class="pi-links">
        <%= link_to product_path(product.id), class: "add-card" do %>
          <i class="flaticon-bag"></i><span>ADD TO CART</span>
        <% end %>
      </div>
    </div>
    <div class="pi-text">
      <h6><%= product.discounted_price %>$</h6>
      <p><%= product.product_name %></p>
    </div>
  </div>
</div>

app/views/products/_recommend_by_like.html.erb
<div class="col-lg-3 col-sm-6">
  <div class="product-item">
    <div class="pi-pic">
      <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
      <div class="pi-links">
        <a href="#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
      </div>
    </div>
    <div class="pi-text">
      <h6><%= product.discounted_price %>$</h6>
      <p><%= product.product_name %></p>
    </div>
  </div>
</div>

app/views/products/_top_review.html.erb
<% @top_reviews[0..2].each do |product| %>
  <div class="card" style="margin-top: 10px;">
    <%= link_to image_tag( product.image.split(/,/).first, class: "card-img-top", style: "width: 200px; height: 160px;"), product_path(product) %>
    <div class="card-body">
      <h5 class="card-title"><%= product.product_name %></h5>
      <p class="product-description"><%= product.description %></p>
      <div class='star-rating' data-score=<%= product.overall_rating %>></div>
    </div>
  </div>
<% end %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/flip_flops_product.html.erb
<body>
  <section class="product-filter-section">
    <div class="container">
      <br>
      <div class="section-title">
        <h2>FLIP FLOPS PRODUCTS</h2>
      </div>

      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item"><%= link_to_prev_page @products, "Previous", class: "page-link" %></li>
          <li class="page-item"><%= link_to_next_page @products, "Next", class: "page-link" %></li>
        </ul>
      </nav>

      <br>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-lg-3 col-sm-6">
            <div class="product-item">
              <div class="pi-pic">
                <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
                <div class="pi-links">
                  <%= link_to product_path(product.id), class: "add-card" do %>
                    <i class="flaticon-bag"></i><span>ADD TO CART</span>
                  <% end %>
                  <div class="product-favorite" id="favorite-icon-product-<%= product.id.to_s %>">
                    <%= render "favorite_icon", {is_favorited: product.is_favorited(current_user), product: product} %>
                  </div>
                </div>
              </div>
              <div class="pi-text">
                <h6><%= product.discounted_price %>$</h6>
                <p><%= product.product_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</body>

app/views/products/product_for_men.html.erb
<body>
  <section class="product-filter-section">
    <div class="container">
      <br>
      <div class="section-title">
        <h2>PRODUCTS FOR MEN</h2>
      </div>

      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item"><%= link_to_prev_page @products, "Previous", class: "page-link" %></li>
          <li class="page-item"><%= link_to_next_page @products, "Next", class: "page-link" %></li>
        </ul>
      </nav>

      <br>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-lg-3 col-sm-6">
            <div class="product-item">
              <div class="pi-pic">
                <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
                <div class="pi-links">
                  <%= link_to product_path(product.id), class: "add-card" do %>
                    <i class="flaticon-bag"></i><span>ADD TO CART</span>
                  <% end %>
                  <div class="product-favorite" id="favorite-icon-product-<%= product.id.to_s %>">
                    <%= render "favorite_icon", {is_favorited: product.is_favorited(current_user), product: product} %>
                  </div>
                </div>
              </div>
              <div class="pi-text">
                <h6><%= product.discounted_price %>$</h6>
                <p><%= product.product_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</body>

app/views/products/sandals_product.html.erb
<body>
  <section class="product-filter-section">
    <div class="container">
      <br>
      <div class="section-title">
        <h2>SANDALS PRODUCTS</h2>
      </div>

      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item"><%= link_to_prev_page @products, "Previous", class: "page-link" %></li>
          <li class="page-item"><%= link_to_next_page @products, "Next", class: "page-link" %></li>
        </ul>
      </nav>

      <br>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-lg-3 col-sm-6">
            <div class="product-item">
              <div class="pi-pic">
                <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
                <div class="pi-links">
                  <%= link_to product_path(product.id), class: "add-card" do %>
                    <i class="flaticon-bag"></i><span>ADD TO CART</span>
                  <% end %>
                  <div class="product-favorite" id="favorite-icon-product-<%= product.id.to_s %>">
                    <%= render "favorite_icon", {is_favorited: product.is_favorited(current_user), product: product} %>
                  </div>
                </div>
              </div>
              <div class="pi-text">
                <h6><%= product.discounted_price %>$</h6>
                <p><%= product.product_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</body>

app/views/products/show.html.erb
<div class="page-top-info">
  <div class="container">
    <h4>Category PAge</h4>
    <div class="site-pagination">
      <%= @product.product_category_tree %>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- product section -->
<section class="product-section">
  <div class="container">
    <div class="back-link">
      <a href="/"> &lt;&lt; Back to Category</a>
    </div>
    <div class="row">
      <div class="col-lg-6">

        <div class="product-item">
          <div class="pi-pic">
            <div class="product-pic-zoom">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <% @product.image.split(/,/).each do |product, index| %>
                    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>"></li>
                  <% end %>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img><%= image_tag(@product.image.split(/,/).first, class: "product-big-img", style: "width: 690px; height: 800px; float: center;") %>
                  </div>

                  <% @product.image.split(/,/)[1...@product.image.split(/,/).size].each do |image, index| %>
                    <div class="carousel-item">
                      <img><%= image_tag(image, class: "product-big-img", style: "width: 690px; height: 800px; float: center;") %>
                    </div>
                  <% end %>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: black;"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: black;"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <div class="pi-links">
            <div class="product-favorite" id="favorite-icon-product-<%= @product.id.to_s %>">
                <%= render "products/favorite_icon", {is_favorited: @product.is_favorited(current_user), product: @product} %>
              </div>
            </div>
          </div>
        </div>

        <div class="product-thumbs" tabindex="1" style="overflow: hidden; outline: none;">
          <div class="row" style="margin: auto;">
            <div class="product-thumbs-track">
                <% @product.image.split(/,/).each do |a| %>
                  <div class="col pt img-thumbnail" style="margin-top: 5px;" data-imgbigurl="<%= a %>"><img><%= image_tag(a) %></div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 product-details">
        <h2 class="p-title"><%= @product.product_name %></h2>
        <h3 class="p-price"><%= @product.discounted_price %>$</h3>
        <span>Brand: </span><h3><%= @product.brand %></h3>
        <h4 class="p-stock">Available: <span>In Stock</span></h4>
        <div class="p-rating">
          <% @product.reviews.average(:product_rating).to_i.times do %>
          <i class="fa fa-star-o"></i>
          <% end %>
          <% (5- @product.reviews.average(:product_rating).to_i).times do %>
          <i class="fa fa-star-o fa-fade"></i>
          <% end %> | <%= @product.reviews.average(:product_rating) || 0 %>
        </div>


        <div class="p-review">
          <a data-toggle="modal" data-target="#exampleModalScrollable">
            <%= @product.reviews.size %> reviews
          </a>

          <!-- Modal -->
          <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalScrollableTitle">REVIEWS</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <% if @reviews.size == 0 %>
                    No reivews
                  <% else %>
                    <% @reviews.each do |review| %>
                      <div class="reviews">
                        <strong><%= review.user.email %></strong>
                        <p style="color: #999; float: right;"><%= time_ago_in_words(review.created_at).upcase %> AGO</p>
                        <div class="star-rating" data-score= <%= review.product_rating %> ></div>
                        <p><%= review.comment %></p>
                        <% if user_signed_in? %>
                          <% if current_user.id == review.user_id %>
                            <%= link_to edit_product_review_path(review.product, review) do %>
                              <ion-icon name="create"></ion-icon>
                            <% end %>
                            <%= link_to review_path(review), method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <ion-icon name="trash"></ion-icon>
                            <% end %>
                          <% end %>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          <% if user_signed_in? %>
            <% if !Review.find_by(user_id: current_user.id, product_id: @product.id) %>
              | <%= link_to "Add your review", new_product_review_path(@product) %>
            <% end %>
          <% end %>
        </div>
        <div class="fw-size-choose">
          <p>Size</p>
          <div class="sc-item">
            <input type="radio" name="sc" id="s-size">
            <label for="s-size">S</label>
          </div>
          <div class="sc-item">
            <input type="radio" name="sc" id="m-size" checked="">
            <label for="m-size">M</label>
          </div>
          <div class="sc-item">
            <input type="radio" name="sc" id="l-size">
            <label for="l-size">L</label>
          </div>
          <div class="sc-item">
            <input type="radio" name="sc" id="xl-size">
            <label for="xl-size">XL</label>
          </div>
          <div class="sc-item">
            <input type="radio" name="sc" id="xxl-size">
            <label for="xxl-size">XXL</label>
          </div>
        </div>
        <div class="quantity">
          <p>Quantity</p>
          <div class="pro-qty">
            <input type="text" value="1" readonly style="align: center">
          </div>
        </div>

        <!-- <a href="#" class="site-btn">SHOP NOW</a> -->
        <%= button_to 'Add to Cart',
                          line_items_path(:product_id => @product), class: "site-btn",
                          :remote => true %>

        <div id="accordion" class="accordion-area">
          <div class="panel">
            <div class="panel-header" id="headingOne">
              <button class="panel-link active" data-toggle="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">information</button>
            </div>
            <div id="collapse1" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="panel-body">
                <p><%= @product.description %></p>
              </div>
            </div>
          </div>
          <div class="panel">
            <div class="panel-header" id="headingTwo">
              <button class="panel-link" data-toggle="collapse" data-target="#collapse2" aria-expanded="false" aria-controls="collapse2">care details </button>
            </div>
            <div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="panel-body">
                <img src="<%= image_path("cards.png") %>">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra tempor so dales. Phasellus sagittis auctor gravida. Integer bibendum sodales arcu id te mpus. Ut consectetur lacus leo, non scelerisque nulla euismod nec.</p>
              </div>
            </div>
          </div>
          <div class="panel">
            <div class="panel-header" id="headingThree">
              <button class="panel-link" data-toggle="collapse" data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">shipping & Returns</button>
            </div>
            <div id="collapse3" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
              <div class="panel-body">
                <h4>7 Days Returns</h4>
                <p>Cash on Delivery Available<br>Home Delivery <span>3 - 4 days</span></p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra tempor so dales. Phasellus sagittis auctor gravida. Integer bibendum sodales arcu id te mpus. Ut consectetur lacus leo, non scelerisque nulla euismod nec.</p>
              </div>
            </div>
          </div>
        </div>

        <div class="social-sharing">
          <a href=""><i class="fa fa-google-plus"></i></a>
          <a href=""><i class="fa fa-pinterest"></i></a>
          <a href=""><i class="fa fa-facebook"></i></a>
          <a href=""><i class="fa fa-twitter"></i></a>
          <a href=""><i class="fa fa-youtube"></i></a>
        </div>
      </div>
    </div>

    <% if @similar_products.size %>
      <br>
    <br>
    <div class="dropdown-divider"></div>
    <br>
    <br>

    <div>
      <div class="section-title">
        <h2>SIMILAR PRODUCTS</h2>
      </div>
      <div class="row">
        <%= render "product", {product: @product1}%>
        <%= render "product", {product: @product2}%>
        <%= render "product", {product: @product3}%>
        <%= render "product", {product: @product4}%>
      </div>
    </div>
    <% else %>
    sadsa
    <% end %>

    <% if recent_products.size != 0 %>
      <br>
      <br>
      <div class="dropdown-divider"></div>
      <br>
      <br>

      <div>
        <div class="section-title">
          <h2>RECENT PRODUCTS</h2>
        </div>
        <div class="row">
          <% recent_products.reverse.each do |product| %>
            <%= render "product", {product: product}%>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
</section>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/products/sneakers_product.html.erb
<body>
  <section class="product-filter-section">
    <div class="container">
      <br>
      <div class="section-title">
        <h2>SNEAKERS PRODUCTS</h2>
      </div>

      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
          <li class="page-item"><%= link_to_prev_page @products, "Previous", class: "page-link" %></li>
          <li class="page-item"><%= link_to_next_page @products, "Next", class: "page-link" %></li>
        </ul>
      </nav>

      <br>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-lg-3 col-sm-6">
            <div class="product-item">
              <div class="pi-pic">
                <%= link_to image_tag(product.image.split(/,/).first, class: "image-product"), product_path(product.id) %>
                <div class="pi-links">
                  <%= link_to product_path(product.id), class: "add-card" do %>
                    <i class="flaticon-bag"></i><span>ADD TO CART</span>
                  <% end %>
                  <div class="product-favorite" id="favorite-icon-product-<%= product.id.to_s %>">
                    <%= render "favorite_icon", {is_favorited: product.is_favorited(current_user), product: product} %>
                  </div>
                </div>
              </div>
              <div class="pi-text">
                <h6><%= product.discounted_price %>$</h6>
                <p><%= product.product_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</body>