config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :orders
  resources :line_items
  resources :carts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users do
    resources :reviews
  end

  resources :products do
    resources :reviews
    resources :favorites, only: [:create, :destroy], shallow: true
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'

  get "search", to: "search#search"

  get "purchase_history", to: "users#purchase_history"
  get "chat", to: "users#chat"
  get "admin_products", to: "users#admin_products"
  get "admin_users", to: "users#admin_users"
  get "admin_orders", to: "users#admin_orders"

  get "product_for_women", to: "products#product_for_women"
  get "product_for_men", to: "products#product_for_men"
  get "sneakers_product", to: "products#sneakers_product"
  get "sandals_product", to: "products#sandals_product"
  get "shoes_product", to: "products#shoes_product"
  get "boots_product", to: "products#boots_product"
  get "flip_flops_product", to: "products#flip_flops_product"

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end

  get "recommend_product", to: "users#recommend_product"

  get "cf_product", to: "users#cf_product"

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    price_unit * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
    @cart = current_cart
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
    @cart = current_cart
    @line_item = current_cart.line_items.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    @line_item.price_unit = product.discounted_price

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to('/', :notice => 'Line item was successfully created') }
        format.js   { @current_item = @line_item, flash[:notice] = "Product was added to cart" }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end

    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @cart = @line_item.cart

    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @cart, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = @line_item.cart
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @cart, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id, :price_unit, :quantity)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :line_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.number_field :cart_id, id: :line_item_cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td class="product-col">
    <img><%= image_tag(line_item.product.image.split(/,/).first) %>
    <div class="pc-title">
      <h4><%= line_item.product.product_name %></h4>
      <p>$<%= line_item.price_unit %></p>
    </div>
  </td>
  <td class="quy-col">
    <div class="quantity">
      <div class="pro-qty">
        <input type="text" value="<%= line_item.quantity %>" readonly>
      </div>
    </div>
  </td>
  <td class="size-col"><h4>Size M</h4></td>
  <td class="total-col"><h4><%= number_to_currency(line_item.total_price) %></h4></td>
  <td>
    <%= link_to edit_line_item_path(line_item) do %>
      <ion-icon name="create"></ion-icon>
    <% end %>
    <%= link_to line_item_path(line_item), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <ion-icon name="trash"></ion-icon>
    <% end %>
  </td>
</tr>

app/views/line_items/create.js.erb
$("#cart-header").html('<%= j render "shared/cart_header" %>');

app/views/line_items/edit.html.erb
<%= form_with(model: @line_item, local: true) do |form| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="page-top-info">
    <div class="container">
      <h4>Your cart</h4>
      <div class="site-pagination">
        <a href="">Home</a> /
        <a href="">Your cart</a>
      </div>
    </div>
  </div>
  <!-- Page info end -->


  <!-- cart section end -->
  <section class="cart-section spad">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="cart-table">
            <h3>Edit Line Item </h3>
            <div class="cart-table-warp">
              <table>
                <thead>
                  <tr>
                    <th class="product-th">Product</th>
                    <th class="quy-th">Quantity</th>
                    <th class="size-th">Size</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td class="product-col">
                        <img><%= image_tag(@line_item.product.image.split(/,/).first) %>
                        <div class="pc-title">
                          <h4><%= @line_item.product.product_name %></h4>
                          <p>$<%= @line_item.price_unit %></p>
                        </div>
                      </td>
                      <td class="quy-col">
                        <div class="quantity">
                          <div class="pro-qty">
                            <div class="form-group row">
                                <%= form.number_field :quantity, value: 1, class: 'form-control' %>
                              <div>
                            </div>
                          </div>
                        </div>
                      </td>
                      <td class="size-col"><h4>Size M</h4></td>
                    </tr>
                </tbody>
              </table>
            </div>
            <div>
              <%= form.submit "Update", class: "btn btn-primary" %>
              <%= link_to "Back", cart_path(@cart), class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- cart section end -->

  <!-- Related product section -->
  <section class="related-product-section">
    <div class="container">
      <div class="section-title text-uppercase">
        <h2>Continue Shopping</h2>
      </div>
      <div class="row">
        <% 4.times do %>
          <%= render "products/random_product", {product: random_product } %>
        <% end %>
      </div>
    </div>
  </section>

<% end %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>